M48
; DRILL file {KiCad (7.0.0)} date Wed Jun 28 20:41:32 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-28T20:41:32+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X6.0423Y-2.9662
T1
G00X5.811Y-2.9662
M15
G01X5.8011Y-2.9662
M16
G05
T0
M30
